---
title       : Prediction of child's height 
subtitle    : Galton-app presentation using slidify
author      : Tran Manh Hien
job         : Coursera MOOC's Data Science student
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [mathjax]     # {mathjax, quiz, bootstrap}
mode        : standalone    # {standalone, draft, selfcontained}
knit        : slidify::knit2slides
---

## Introduction
   
   
- ganton-app predicts child's height at adult age from parents height(s) and child's gender.
- The model is fitted from data based on the famous 1885 study by Sir Francis Galton.
- The fitted linear model is quite accurate and it was claimed that the model can challenge modern genomic studies [(Predicting human height by Victorian and genomic methods, Nature 2009)](http://www.nature.com/ejhg/journal/v17/n8/full/ejhg20095a.html) 
- The app was created using RStudio's shiny package and deployed at shinyapps.io
 + Simplicity in development.
 + Easy to use.
 + Deployment in Internet for accessibility.
 + Scalability: computers and mobile platforms.  
- Run from [here](https://hien.shinyapps.io/galton-app)


--- .class #id 

## Data
   
   
- Full [dataset](http://www.math.uah.edu/stat/data/Galton.html) was downloaded from the University of Alabama in Huntsville website.   
- Data related to parents's heights, childrens' genders and heights are retained.   

```{r}
require(utils)
download.file("http://www.math.uah.edu/stat/data/Galton.csv","Galton.csv",method="auto", quiet=TRUE)
gdata <- read.csv("Galton.csv", stringsAsFactors = FALSE)
## strip-off unused columns
gdata <- gdata[,c(2:5)]
head(gdata,5)
```

---

## Fitting Models and Prediction

- For simplicity we fit 3 linear regression models using $lm()$ function:
 1. Child's height ~ both parents' height and child's gender 
 $$Y_i =  \beta_0 + \beta_1 X_{1i} + \beta_2 X_{2i} + \beta_3 X_{3i}$$
 2. Child's height ~ father's height and child's gender
 3. Child's height ~ mother's height and child's gender
- All models intercepts and slopes are significant with $p-values$ < 0.001
- Depending on user's selection for prediction based on both parents' heights, or only individual parent's height, the respective fitted model will be selected.
- Prediction using $predict.lm()$ function with the confidence level given by user for prediction inteval.

---

## Easy to Use

- Run from this link [https://hien.shinyapps.io/galton-app](https://hien.shinyapps.io/galton-app)
- Enter/select parameters:
 + Prediction based on both parents heights or only one of them.
 + Use slider(s) to select parents heights.
 + Choose child's gender.
 + Change confidence level as needed. By default it is 95%

- The app immediatelly responds to user's change of parameters.
- Predicted height and prediction interval are displayed.
- Bar graph to compare child's height and prediction interval with parents heights.

$$Thanks$$
